service: tv-list-api
provider:
  name: aws
  runtime: nodejs12.x
  stage: production
  region: eu-west-2
  memorySize: 128
  timeout: 10
plugins:
  - serverless-bundle
  - serverless-dotenv-plugin
  - serverless-plugin-include-dependencies
package:
  individually: true
functions:
  app:
    handler: serverless-app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /login
          method: POST
          cors: true
      - http: 
          path: /stored-shows
          method: GET
          cors:
              origin: '*'
              headers:
                - x-access-token
      - http: 
          path: /archived-shows
          method: GET
          cors:
              origin: '*'
              headers:
                - x-access-token
      - http: 
          path: /stored-shows
          method: POST
          cors: true
      - http: 
          path: /archived-shows
          method: POST
          cors: true
      - http: 
          path: /current
          method: GET
          cors:
              origin: '*'
              headers:
                - x-access-token
      - http: 
          path: /user
          method: POST
          cors: true